### ISSUE TITLE
Docker Repo out of sync with GitHub repo

### ISSUE THREAD

**Issue by tomstockton** [cloudbees/jenkins-ci.org-docker#38]
Forgive my ignorance, however it appears that the Jenkins images available from https://registry.hub.docker.com/_/jenkins/ are not up to date with the files that are maintained here (github).

For example I want to take advantage of the ```plugins.sh``` script to add new plugins, when I click through the link for the latest (1.565.3) dockerfile (https://github.com/cloudbees/jenkins-ci.org-docker/blob/f744bdb73fbfc701a52105460511284a470bcfb8/Dockerfile) then I can see that it does not include the ```COPY plugins.sh``` line that I would expect as seen here: https://github.com/cloudbees/jenkins-ci.org-docker/blob/master/1.565.3/Dockerfile

Am I missing something or do the Jenkins images in the official docker repo need updating?

**Comment by gcaracuel** [comment]
Not working for me because the COPY maybe failed, I'm noob with Docker.

exec: "/usr/local/bin/jenkins.sh": permission denied
