### ISSUE TITLE
Add sudo without password to image

### ISSUE THREAD

**Issue by XANi** [cloudbees/jenkins-ci.org-docker#39]
many non-java projects need to have additional deps installed to build but there is no option to automate it from jenkins as there is no sudo installed.

Sudo without password would allow to just add sth like:

    if [ ! -e /usr/bin/make ] ; then
        sudo apt-get update &&   sudo apt-get install -y build-essential
    fi

to build script to install needed deps for C app

**Comment by nocquidant** [comment]
+1

I tried to install Maven with `RUN apt-get install -y maven` but I can't extend this image...
Jenkins user should also be a sudoer.

Thanks,
/Nick

**Comment by yarikoptic** [comment]
README has it:  https://github.com/cloudbees/jenkins-ci.org-docker#installing-more-tools
Enabling by default sudo access to jenkins user is a security hazard happen this container listens on public IP

**Comment by XANi** [comment]
As is starting jenkins with default password...

**Comment by ndeloof** [comment]
just create a derived Docker image to install additional tools
About default password, this image is intended for customization (just like a plain jenkins download) and does start in "all user can do anything", up to you to configure security, which configuration is stored in jenkins_home
