### ISSUE TITLE
Inability to copy files from within the official Jenkins Image to the docker host

### ISSUE THREAD

**Issue by romant** [cloudbees/jenkins-ci.org-docker#40]
### Issue

From the [official Jenkins Docker Hub Repo instructions](https://registry.hub.docker.com/_/jenkins/)

>If your volume is inside a container - you can use ```docker cp $ID:/var/jenkins_home ```
>command to extract the data.

Unfortunately this doesn't function as expected.

#### On the Host
```sh
$ docker pull jenkins
$ docker run -p 2375:8080 -t jenkins
$ docker cp [container_id | name]:/var_jenkins_home .
```

##### Expectation
have the ```var_jenkins_home``` directory be copied to the docker host
##### Actual
the following is present / copied

```sh
.bash_logout
.bashrc
.profile
````

### Next Steps
Please advise whether this is expected behavior, and simply a matter of mis-understanding, or an issue to be addressed. Thank you.

### Environment
```sh
$ docker version
Client version: 1.3.3
Client API version: 1.15
Go version (client): go1.3.2
Git commit (client): 5dc1c5a
OS/Arch (client): linux/amd64
Server version: 1.3.3
Server API version: 1.15
Go version (server): go1.3.2
Git commit (server): 5dc1c5a
```

**Comment by jolexa** [comment]
Hi, I found this https://github.com/docker/docker/issues/7372 and confirmed it to be true. I was using version 1.3.3 and when I upgraded to 1.5.0 the copy function was recursive as expected. Hope that helps.
