### ISSUE TITLE
firewall related issues and network connectivity with latest git version

### ISSUE THREAD

**Issue by yvnicolas** [cloudbees/jenkins-ci.org-docker#41]
Server running on Ubuntu 14.01, I installed docker following docker installation document https://docs.docker.com/installation/ubuntulinux/ for latest version in docker 
Got a 1.4 docker version
The jenkins official image is not able to access external world when the firewall is based on DROP main policy.
Everything is fine when  I get back to earlier versions of docker

**Comment by ndeloof** [comment]
Seems to be a docker issue then, please ask on docker mailing list
