### ISSUE TITLE
Please update to latest Jenkins release

### ISSUE THREAD

**Issue by pinguinkiste** [cloudbees/jenkins-ci.org-docker#59]
Since a new Jenkins version has been releast, a fresh <code>jenkins:latest</code> container "complains" that it's outdated. Please provide the most recent version to match upstream.

Best regards,

Manuel

**Comment by killuazhu** [comment]
+1

**Comment by brianredbeard** [comment]
FYI, best not to reference versions as at this point even the version in the issue subject is out of date.

**Comment by anpieber** [comment]
Is there anyone actively maintaining this package? Actually will pull requests with newer versions be accepted?

**Comment by pinguinkiste** [comment]
Thanks for the hint, @brianredbeard! I updated the description accordingly.

**Comment by ndeloof** [comment]
I'm working to get recent released deployed but the "official image" process is based on manual review which slows down the process

**Comment by pinguinkiste** [comment]
Thanks for clarifying and for your work on this!
