### ISSUE TITLE
Cannot update or change config manualy 

### ISSUE THREAD

**Issue by taiffu** [cloudbees/jenkins-ci.org-docker#64]
When access to jenking container example via exec bash enviroment
need root privileges but is not possible.
 
docker exec -it [container_id] bash

Example there is no sudo or su to root user does not work
su command gives error
su: must be run from a terminal

Sudo or root access is need for make config manualy or update .war file to 
container.

**Comment by yarikoptic** [comment]
export TERM=vt100 would bring piece of those commands needing term

**Comment by amouat** [comment]
I use my own build based off Jenkins that gives sudo rights to the jenkins user. The Dockerfile looks like:

```
FROM jenkins:1.596

USER root
RUN apt-get update \
      && apt-get install -y sudo \
      && rm -rf /var/lib/apt/lists/*
RUN echo "jenkins ALL=NOPASSWD: ALL" >> /etc/sudoers

USER jenkins
COPY plugins.txt /usr/share/jenkins/plugins.txt
RUN /usr/local/bin/plugins.sh /usr/share/jenkins/plugins.txt
```

**Comment by ndeloof** [comment]
You should not update .war file, but just change the docker image version you run.
About configuration, it is all stored in JENKINS_HOME so doesn't need to be root for edition.

**Comment by scmgalaxy** [comment]
BTW, I want to install some of the other tools using root or sudo but when i try to login i get the error "su: must be run from a terminal" . How can i get rid of this issues?

**Comment by ndeloof** [comment]
Write a Dockerfile to extend the jenkins one:
```
FROM jenkins
USER root
CMD install stuff as root
USER jenkins
```

**Comment by adampats** [comment]
FWIW, I was able to work around this (needed to install some tools) by using `docker cp` from the host - this copies the files as root.

**Comment by gbonk** [comment]
This worked for me

docker exec -u root -it [container_id] bash

**Comment by solairerove** [comment]
lol. ty

**Comment by scott-sherwood** [comment]
Thanks @gbonk worked a treat
