### ISSUE TITLE
How to set context path in jenkins

### ISSUE THREAD

**Issue by manoj150283** [cloudbees/jenkins-ci.org-docker#68]

**Comment by ndeloof** [comment]
Why would you need this ?

**Comment by manoj150283** [comment]
I needed this to access my jenkins instance using context path e.g. www.abc.com/jenkins. Anyway I resolved it by passing jenkins launcher arguments **--prefix=/jenkins** at the end.

**Comment by LouisAtNantes** [comment]
To complete the final answer, if you want to do this in a _docker-compose.yml_ file: 
```
...
jenkins:
    container_name: jenkins_test
    environment:
      - JENKINS_OPTS="--prefix=/jenkins"
...
```
