### ISSUE TITLE
plugin.txt fails to load git-client

### ISSUE THREAD

**Issue by davehun** [cloudbees/jenkins-ci.org-docker#84]
the git-client plugin fails to load correctly when added to plugins.txt:
the plugin.txt below is fails to load git-client and anything that depends on it

    scm-api:0.2
    git:2.3.5
    git-client:1.16.1
    github:1.11.3
    github-api:1.67
    github-oauth:0.20

from the logs
    
    SEVERE: Failed Inspecting plugin /var/jenkins_home/plugins/git-client.hpi
        java.io.IOException: Failed to expand /var/jenkins_home/plugins/git-client.hpi
    ...
    ...
    Caused by: Error while expanding /var/jenkins_home/plugins/git-client.hpi
         java.util.zip.ZipException: archive is not a ZIP archive
	     at org.apache.tools.ant.taskdefs.Expand.expandFile(Expand.java:192)

**Comment by carlossg** [comment]
You probably got a corrupted `/var/jenkins_home/plugins/git-client.hpi`

**Comment by davehun** [comment]
yep wiping out /var/jenkins_home/ caused it to run ok.
Thanks
